#!/usr/bin/env bash
# to automatically apply repo changes, on a new machine run
# cp pre-commit post-commit .git/hooks/
cd "$(git rev-parse --show-toplevel)" && nix run .config/home-manager -- switch --flake .config/home-manager#jeremyp
