#!/usr/bin/env bash
# to automatically apply repo changes, on a new machine run
# cp pre-commit post-commit .git/hooks/
cd "$(git rev-parse --show-toplevel)/.config/home-manager" && nix fmt . && git add -u .
