local treesitter = require 'nvim-treesitter.configs'
local installer = require 'nvim-treesitter.install'

treesitter.setup {
  ensure_installed = {
    "ada",
    "agda",
    -- "arduino",
    "astro",
    "awk",
    "bash",
    "beancount",
    "bibtex",
    "blueprint",
    "c",
    "c_sharp",
    "capnp",
    "clojure",
    "cmake",
    "comment",
    "commonlisp",
    "cooklang",
    "cpp",
    "css",
    "cuda",
    "dart",
    "diff",
    "dockerfile",
    "dot",
    "ebnf",
    "eex",
    "elixir",
    "elm",
    "elvish",
    "embedded_template",
    "erlang",
    "fennel",
    "fish",
    "foam",
    "fortran",
    "fsh",
    "fusion",
    "gdscript",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gleam",
    "glimmer",
    "glsl",
    "go",
    "gomod",
    "gowork",
    "graphql",
    "hack",
    "haskell",
    "hcl",
    "heex",
    "hjson",
    "hlsl",
    "hocon",
    "html",
    "htmldjango",
    "http",
    "ini",
    "java",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "json5",
    "jsonc",
    "jsonnet",
    "julia",
    "kotlin",
    "lalrpop",
    "latex",
    "ledger",
    "llvm",
    "lua",
    "m68k",
    "make",
    "markdown",
    "markdown_inline",
    "menhir",
    "mermaid",
    "meson",
    "nickel",
    "ninja",
    "nix",
    -- "norg",
    "ocaml",
    "ocaml_interface",
    -- "org",
    "pascal",
    "perl",
    "php",
    "phpdoc",
    "pioasm",
    "poe_filter",
    "prisma",
    "proto",
    "pug",
    "python",
    "ql",
    "qmljs",
    "query",
    "r",
    "racket",
    "rasi",
    "regex",
    "rego",
    "rnoweb",
    "rst",
    "ruby",
    "rust",
    "scala",
    "scheme",
    "scss",
    "slint",
    "smali",
    "solidity",
    "sparql",
    "supercollider",
    "surface",
    "svelte",
    "sxhkdrc",
    "t32",
    "terraform",
    "thrift",
    "tiger",
    "tlaplus",
    "todotxt",
    "toml",
    "tsx",
    "turtle",
    "twig",
    "typescript",
    "v",
    "vala",
    "verilog",
    "vhs",
    "vim",
    "vimdoc",
    "vue",
    "wgsl",
    "wgsl_bevy",
    "yaml",
    "yang",
    "zig",
  },
  sync_install = false,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = true,
  },
  rainbow = {
    enable = true,
    extended_mode = true,
  },
  indent = {
    enable = true,
  },
}

-- prefer brew's gcc to Apple's clang
installer.compilers = { "/usr/local/bin/gcc-13", unpack(installer.compilers) }
